/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package saas_cigniti;

/**
 *
 * @author vijju
 */
public class RightProjects extends javax.swing.JPanel {

    /**
     * Creates new form RightProjects
     */
    public RightProjects() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCreateProject = new javax.swing.JButton();
        btnLoadProject = new javax.swing.JButton();
        btnDeleteProject = new javax.swing.JButton();
        btnImportProject = new javax.swing.JButton();
        btnExportProject = new javax.swing.JButton();
        btnConfigProject = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(225, 590));

        btnCreateProject.setIcon(new javax.swing.ImageIcon(getClass().getResource("/saas_cigniti/images/Main/icons8_combo_chart_45px_2.png"))); // NOI18N
        btnCreateProject.setText("Create Project");
        btnCreateProject.setBorder(null);
        btnCreateProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateProjectActionPerformed(evt);
            }
        });

        btnLoadProject.setIcon(new javax.swing.ImageIcon(getClass().getResource("/saas_cigniti/images/Main/icons8_combo_chart_45px_2.png"))); // NOI18N
        btnLoadProject.setText("Load Project");
        btnLoadProject.setBorder(null);
        btnLoadProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadProjectActionPerformed(evt);
            }
        });

        btnDeleteProject.setIcon(new javax.swing.ImageIcon(getClass().getResource("/saas_cigniti/images/Main/icons8_combo_chart_45px_2.png"))); // NOI18N
        btnDeleteProject.setText("Delete Project");
        btnDeleteProject.setBorder(null);
        btnDeleteProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteProjectActionPerformed(evt);
            }
        });

        btnImportProject.setIcon(new javax.swing.ImageIcon(getClass().getResource("/saas_cigniti/images/Main/icons8_combo_chart_45px_2.png"))); // NOI18N
        btnImportProject.setText("Import Project");
        btnImportProject.setBorder(null);
        btnImportProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportProjectActionPerformed(evt);
            }
        });

        btnExportProject.setIcon(new javax.swing.ImageIcon(getClass().getResource("/saas_cigniti/images/Main/icons8_combo_chart_45px_2.png"))); // NOI18N
        btnExportProject.setText("Export Project");
        btnExportProject.setBorder(null);
        btnExportProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportProjectActionPerformed(evt);
            }
        });

        btnConfigProject.setIcon(new javax.swing.ImageIcon(getClass().getResource("/saas_cigniti/images/Main/icons8_combo_chart_45px_2.png"))); // NOI18N
        btnConfigProject.setText("Config Project");
        btnConfigProject.setBorder(null);
        btnConfigProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfigProjectActionPerformed(evt);
            }
        });

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/saas_cigniti/images/Main/icons8_rewind_65px.png"))); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCreateProject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLoadProject, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                    .addComponent(btnDeleteProject, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                    .addComponent(btnImportProject, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                    .addComponent(btnExportProject, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                    .addComponent(btnConfigProject, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(btnCreateProject, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLoadProject, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnDeleteProject, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnImportProject, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnExportProject, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnConfigProject, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoadProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadProjectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLoadProjectActionPerformed

    private void btnCreateProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateProjectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCreateProjectActionPerformed

    private void btnDeleteProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteProjectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteProjectActionPerformed

    private void btnImportProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportProjectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnImportProjectActionPerformed

    private void btnExportProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportProjectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExportProjectActionPerformed

    private void btnConfigProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfigProjectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConfigProjectActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnConfigProject;
    private javax.swing.JButton btnCreateProject;
    private javax.swing.JButton btnDeleteProject;
    private javax.swing.JButton btnExportProject;
    private javax.swing.JButton btnImportProject;
    private javax.swing.JButton btnLoadProject;
    // End of variables declaration//GEN-END:variables
}
