/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package saas_cigniti;

/**
 *
 * @author vijju
 */
public class RightPanel extends javax.swing.JPanel {

    /**
     * Creates new form RightPanel
     */
    public RightPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDashboard = new javax.swing.JButton();
        btnProjects = new javax.swing.JButton();
        btnSmartHub = new javax.swing.JButton();
        btnDashboard4 = new javax.swing.JButton();
        btnReports = new javax.swing.JButton();
        btnReports1 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(225, 590));

        btnDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/saas_cigniti/images/Main/icons8_combo_chart_45px_2.png"))); // NOI18N
        btnDashboard.setText("Dashboard");
        btnDashboard.setBorder(null);

        btnProjects.setIcon(new javax.swing.ImageIcon(getClass().getResource("/saas_cigniti/images/Main/icons8_combo_chart_45px_2.png"))); // NOI18N
        btnProjects.setBorder(null);
        btnProjects.setLabel("Projects");
        btnProjects.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProjectsActionPerformed(evt);
            }
        });

        btnSmartHub.setIcon(new javax.swing.ImageIcon(getClass().getResource("/saas_cigniti/images/Main/icons8_combo_chart_45px_2.png"))); // NOI18N
        btnSmartHub.setBorder(null);
        btnSmartHub.setLabel("Smart Hub");

        btnDashboard4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/saas_cigniti/images/Main/icons8_combo_chart_45px_2.png"))); // NOI18N
        btnDashboard4.setText("Execution Lab");
        btnDashboard4.setBorder(null);

        btnReports.setIcon(new javax.swing.ImageIcon(getClass().getResource("/saas_cigniti/images/Main/icons8_combo_chart_45px_2.png"))); // NOI18N
        btnReports.setText("Reports");
        btnReports.setBorder(null);

        btnReports1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/saas_cigniti/images/Main/icons8_combo_chart_45px_2.png"))); // NOI18N
        btnReports1.setText("Suite Mangement");
        btnReports1.setBorder(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnProjects, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(btnSmartHub, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(btnDashboard4, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(btnReports, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(btnReports1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(84, Short.MAX_VALUE)
                .addComponent(btnDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnProjects, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnSmartHub, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnDashboard4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnReports, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnReports1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnProjectsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProjectsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProjectsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDashboard;
    private javax.swing.JButton btnDashboard4;
    private javax.swing.JButton btnProjects;
    private javax.swing.JButton btnReports;
    private javax.swing.JButton btnReports1;
    private javax.swing.JButton btnSmartHub;
    // End of variables declaration//GEN-END:variables
}
